# Generated by Django 2.2.5 on 2021-06-01 10:59

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('genre_id', models.IntegerField(primary_key=True, serialize=False)),
                ('genre_name', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Music',
            fields=[
                ('track_id', models.IntegerField(primary_key=True, serialize=False)),
                ('filename', models.CharField(max_length=300)),
                ('artist_name', models.CharField(max_length=100)),
                ('album_name', models.CharField(max_length=200)),
                ('song_name', models.TextField()),
                ('release_date', models.DateField()),
                ('bit_rate', models.FloatField()),
                ('features', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), size=None)),
                ('genres', models.ManyToManyField(to='playlist.Genre')),
            ],
        ),
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=10)),
                ('num_listen', models.IntegerField()),
                ('track_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='playlist.Music')),
            ],
        ),
    ]
